spring:
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 3000
          writetimeout: 5000
          connection:
            timeout: 3000
          ssl:
            trust: "*"
  datasource:
    url: jdbc:mysql://localhost:3306/jwt
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true